export default{
  products: [
    {
      _id:'1',
      name:'Full Zip Running Shirt',
      image:'/images/product-1.jpg',
      price: 60,
      brand:'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id:'2',
      name:'Nike full-zip hoodie Mens Workout',
      image:'/images/product-2.jpg',
      price: 90,
      brand:'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id:'3',
      name:'New Shirt',
      image:'/images/product-3.jpg',
      price: 30,
      brand:'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id:'4',
      name:'Other shirt',
      image:'/images/product-4.jpg',
      price: 20,
      brand:'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id:'5',
      name:'New Product',
      image:'/images/product-5.jpg',
      price: 40,
      brand:'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id:'6',
      name:'Best Product',
      image:'/images/product-6.jpg',
      price: 80,
      brand:'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};